FROM nginx:alpine

COPY index.html  /usr/share/nginx/html/index.html
COPY login.html  /usr/share/nginx/html/login.html
COPY cast.js     /usr/share/nginx/html/cast.js
COPY player.js   /usr/share/nginx/html/player.js
COPY style.css   /usr/share/nginx/html/style.css

EXPOSE 80
